AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  graalvm-s3

  Sample SAM Template for graalvm-s3

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  S3GraalVM:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: S3GraalVM
      Handler: helloworld.S3GraalVM::handleRequest
      Runtime: provided.al2
      MemorySize: 512
      Policies:
      - Statement:
        - Sid: S3Access
          Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
      Environment:
        Variables:
          S3Bucket: !Ref S3Bucket

Outputs:
  S3Bucket:
    Description: "S3Bucket"
    Value: !GetAtt S3Bucket.Arn
  S3GraalVM:
    Description: "S3GraalVM Lambda Function ARN"
    Value: !GetAtt S3GraalVM.Arn